swagger: "2.0"

info:
  version: 1.0.0
  title: API
  description: API for Saved Searches

schemes:
  - http
host: 10.25.9.232:5000
basePath: /api

paths:
  /getSavedSearches:
    get:
      summary: Gets saved searches
      description: Returns a list containing all saved searches.
      responses:
        200:
          description: A list of Saved Searches
          schema:
            type: array
            items:
              required:
                - name
              properties:
                id:
                  type: number
                name:
                  type: string